### ISSUE TITLE
Micro quantization options for SWING

### ISSUE THREAD

**Issue by vcvrackideas** [Stubs42/OrangeLine#11]
Hi and thanks for your modules! Just realized how cool Swing is. Maybe you will find it a bit out of your humanization conception but here is the suggestion after working with the module - what about adding option which would allow user to quantize microtiming to 256, 128, 64 values to prevent out of time tuning when it's needed? Those values can show themselves in tooltips when the function is activated in right click menu instead of percentage of unquantized microtiming values. What do you think about it?

**Comment by Stubs42** [comment]
Hi,
Sry for the late answer. Didn't look here for quite a time. Did some thinking on your request. Since quantizing of time shifts would be heavily influenced by the amount knob, unexpected results would be very often. Swing wasn't developed to place steps on intermediate clock steps to virtually raise clock resolution. So you never will be able to play at a 1/32 timing if your clock runs at 1/16 steps. The goal of Swing is to allow for groovy timing which is from my point of view not quantizable. You always can raise your clock division and use a sequencer capable of defining 32, 48, 64 or any number in between steps for a beat. Thats why I decided to not implement your request.
