### ISSUE TITLE
Seed knob on DejaVu 23.10.resets to input value when module is reset

### ISSUE THREAD

**Issue by fractalgee** [Stubs42/OrangeLine#16]
When I reset DejaVu it also resets the knob for the seed to whatever value the seed input was when reset was processed. The knob should stay where it was as I am sending a bidirectional signal and want the knobs at 50000 (center) so seed modulates all the way left and right of center. This is the first time I have seen a knob get reset when module was reset, That should only happen on initialise

**Comment by Stubs42** [comment]
Ill have a look at this

**Comment by fractalgee** [comment]
I should add that I am on MacOS (11.6.2), just in case that might make some difference

**Comment by Stubs42** [comment]
Oh, the seed cv isn't working in the plugin library release anyway because a bug fixed in 2.3.11. There is a windows build for download the 2.3.11 pre release and you can build your own from the 2.0 branch latest. since there is every seed produces a different output it does not make sense to 'modulate' the seed. That's why the seed input takes over when connected and the seed knob will get disabled. That's why the seed knob resets to 0 if a seed input is connected.

**Comment by fractalgee** [comment]
OK, hmmm, not sure that is expected behaviour, just leave the knob where it is seems more 'expected' behavior, and if knob could become the centerpoint for the modulation that would be awesome. I like to slowly modulate the seed and that way get an ever changing set of melodies. That way the seed knob becomes sort of an offset control for the CV in, so left offsets input negatively, right positively from center for example (and knob stays put at 50000). In my humble opinion, modulate everything ;) if there is a CV I want to use it at some point it always turns out. Random is my game, controlled random even better but only controlled to a point

Awesome module that and must spend time with the others but this and mother do the trick otherwise nicely. Next is swing and gator methinks, but do consider the change of how the CV and knob for Seed work please, 'as one would expect' is always the preferred way of that ;)

**Comment by Stubs42** [comment]
I'll on my way changing the behavior of the seed knob. Will release to plugin library today.
