### ISSUE TITLE
FENCE/RESC - how to move step along with MOTHER child scale?

### ISSUE THREAD

**Issue by bram2000** [Stubs42/OrangeLine#25]
Hi again,

Still loving your modules and really diving deep into what they are capable of.

I'm trying to setup a patch where I have a twelvekey (or any other V/Oct source; sequencer etc.) controlling the _child_ scale of MOTHER. This works great on it's own.

Now I'd like to further control the _step_ value in FENCE to lock to the root note of the _child_ scale from MOTHER. This is where I hit some issues. If I patch twelvekey straight into FENCE that simply won't work, as it will allow me to select notes that are not a part of the MOTHER scale (first screenshot).

I've tried routing the output of twelvekey through a copy of MOTHER (same scale settings), but the only way I can get it working (see second screenshot) is to rescale everything (I've had to set the FENCE _step_ knob manually to get things to marry up) which means that when I hit a _C_ on twelvekey, I actually get an _E_ (the root of the scale). I feel like RESC is the answer to this but I'm not sure how to use it!

Can you provide any tips as to how you'd set this kind of thing up? Thanks!

<img width="811" alt="Screenshot 2024-01-17 at 09 50 35" src="https://github.com/Stubs42/OrangeLine/assets/5268174/0ee2f443-71c9-49fb-8388-ca79b2c7a288">

<img width="787" alt="Screenshot 2024-01-17 at 09 31 35" src="https://github.com/Stubs42/OrangeLine/assets/5268174/09561697-064b-488c-9f2d-f07f037cc6d5">

**Comment by Stubs42** [comment]
Hi,

The child input of mother is relative to root. sending a D on a major mother scale it will always be Dorian. If Root is G then sending a D you get A Dorian. I suppose the following solution:

In the right click menu, set The POW Output Config -> Mode to Scale Pitches and POW Output Config -> Scale Base to Child.
MOTHER will output the child scale at the polyphonic POW output. So channel 1 will be the root note of your child scale.
Since FENCE STEP input is monophonic you do not need a split and you can directly connect the POW output to the STEP input.
Now FENCE STEP should be in sync with MOTHERs CHILD.

Please let me know whether this works for you.

**Comment by bram2000** [comment]
Yes that works perfectly, thank you!

**Comment by bram2000** [comment]
Hi again,

I've hit a similar issue with my setup. I'm trying to use the CV output of a MOTHER instance (used for my main tonic/bass note) to control the _child_ scale of another MOTHER but I can't get it working correctly.

I'm using E Dorian right now and have all of the MOTHER root notes and scales configured the same, but the _child_ input of MOTHER wants the input to be based on C Major (so playing a C to the child input will get my root note of E).

I think I need to use RESC to rescale the output of the first (bass) MOTHER instance from E Dorian to C Major so that I can use it for the _child_ input.

In this case I can't use the POW trick you shared above because I'm not actually changing the child value on the bass MOTHER, just using it as a regular quantizer.

(Not sure if what I'm doing is weird, but maybe it would be good to have Right-click option in MOTHER to set the _child_ input to be absolute rather than relative to C Maj).

Thanks again!

**Comment by Stubs42** [comment]
Hi,
again the POW output may indeed help you. What about using just one MOTHER only. The child input already quantizes so only valid children can be selected. Now just use the first channel 1 of the POW output for your bass which will (with the correct right click menu settings) output always the root note of you selected child scale. Of course you can have any other MOTHER providing the child input of the first one but since this is not directly used as your bass pitch you can easily live with the C-Based child input.
I will think about absolute child input option but cannot promise I will do it.

**Comment by bram2000** [comment]
Ah that sounds like a good option, let me try it and report back. Thanks so much yet again :)

I've just discovered a few modules by Grande (PMR, MS4 and PSplit) which are extremely useful utilities when it comes to using a single polyphonic quantizer for many different voices (different v/Oct and gate sources etc.).
