### ISSUE TITLE
Morpheus + Gator

### ISSUE THREAD

**Issue by paulrobertpine** [Stubs42/OrangeLine#28]
Is it possible to use Gator to add ratchets and jitter to the trigs produced by Morpheus? I like to set Morpheus to produce more "hits" when the GTP knob is turned up, and vice versa. It would be awesome to be able to sequence ratchets on top of this.

**Comment by Stubs42** [comment]
Hi Paul,

Yes, it is but it requires to switch to phased based sequencing.
It maybe take bit to wrap your head around it but when you get it, you maybe will only use phase based sequencing as your main sequencing method.
I added an example patch I created for you to showcase how to use phase based sequencing to solve your request.
Since it is not allowed to upload .vcv files here I reanamed it to be .zip. Rename it to .vcv after downloading to be able to load it in VCV Rack.
Please let me know whether this was helpfull for you.

Regards
Dieter

[RatchetingWithMorpheusAndGator.zip](https://github.com/Stubs42/OrangeLine/files/15052196/RatchetingWithMorpheusAndGator.zip)

**Comment by paulrobertpine** [comment]
Thank you, it's the example patch I was looking for !

**Comment by Stubs42** [comment]
So I close this Issue.
If you have any further questions don't hesitate to contact me.

**Comment by bram2000** [comment]
I've been playing with the example patch and I have a question; why are you using eClk here rather than tClk? If I hook up say a kick drum from CLKD then it wouldn't sync properly with eClk... right?

**Comment by paulrobertpine** [comment]
I didn't understand the delay setting is needed to hear the ratchet. It
makes sense, however I want something simpler so if I want a ratchet of 3 I
can just set something to 3 rather than have to calculate delay time
between notes. So now I'm using Burst  from Befaco for this. I'm still
using Morpheus, but not Swing or Gator for now.

**Comment by Stubs42** [comment]
Hi,
using the eCLK has the advantage that all this eliminates a lot of sample delays because every processing triggered by eCLK is already done when tCLK arrives. In the example patch eCLK is driving MORPHEUS which pus out a gate of (length 1/16th) if there should be a trigger for the current phase. Feeding this gate to GATOR will cause GATOR to output a gate of the length given at the LEN input at the correct time which is identical to tCLK if there is no non 0 input of its TIME input. Think about it like GATOR externnalizes the creation of the tCLK from SWING now allowing  a dedicated microtiming which can be sequenced per step.

**Comment by Stubs42** [comment]
Regarding your other comment, is is fairly easy to to use a small calculation using the formula 1 / (number of ratchets + 1).
just one ratchet use a delay of 0.5 phases. two ratches will need a delay of 0.333 phases and so on.
Hope that helps.
