### ISSUE TITLE
MORPH: The gate output remains high after the clock has been stopped

### ISSUE THREAD

**Issue by anyway** [Stubs42/OrangeLine#29]
For me, this means that the connected oscillator continues to produce sound after the clock has stopped and I have to fade out the patch to get it quiet. I use CLOCKED from IMPROMPTU in this case, but it is similar with other clocks.
I also tried to uncheck "Outputs high on reset when not running" in the CLOCKED menu. Doens't help.

Is this behavior intentional from your side and if so, can it be changed? Or is there some workaround I'm not aware of?

Great modules by the way... thanks for sharing!

MacOS ARM 64
VCV Rack Pro 2.5.1
MORPH 2.4.5

**Comment by Stubs42** [comment]
Hi,
I know quite a later answer. Missed it. Since MORPH has no reset and no more clock is to fuzzy for resetting.
MORPH is deprecated and I would recommend using MORPHEUS instead. Sending a reset will stop all gates MORPHEUS is putting out now after fixing that after reading your issue. Will be out with next release to the library. Including a new module :-)

**Comment by anyway** [comment]
Ah, I see... thanks a lot! :-)
