### ISSUE TITLE
Problem with Orange Line Plugin Mother

### ISSUE THREAD

**Issue by EdwardRosenfeld** [Stubs42/OrangeLine#7]
When I go to change a scale, sometimes the plugin will not change to another scale I choose, I find the only way I can get that change is to hit randomize and then try to add the scale I desire, this can take several tries to accomplish...

**Comment by Stubs42** [comment]
Hi Eddi,
I assume you tried to change the Scale while Child is not 0 (Child Knob turned to the left and no Child CV in). When Child is 0 the Root displays the same note as Child.
This is behaviour by design because scale editing of valid notes is possible only on the mother scale (Child == 0).
Now I see that this might be confusing:
I see three possibilities to avoid this confusion in future releases:
1. I disable the right click Mother Scale select item if Child != 0 (preferred)
2. I allow to change the mother scale if Child != 0 but this will also cause confusion because if Child is set to D with Root C and you select a Major mother scale it will display Dorian because the D Dorian is the daughter scale of C major.
3. Set the mother scale to the selected scale rotated by the current setting of Child. This may result in strange mother scales and I'm not sure whether this is a good idea.
Would you please check whether my assumption is correct ?
If not please give me more detailed information under which condition Mother does not allow to change the scale.
Regards
Dieter

**Comment by Stubs42** [comment]
OrangeLine 1.3.3 will be in plugin manager soon.
Mother Scale selection is disabled on right click menu if effective Child != 0 now.
Also fixes some gcc compatibility problems between my (newer) and the plugin managers build system (older) resulting in faulty Mother and Fence.

**Comment by EdwardRosenfeld** [comment]
Yes, Dieter, you were absolutely correct with regards to the setting I was using, the problem is solved...
